name: Setup WireGuard

on: [push]

jobs:
  setup-wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          private_key: XYZ9876543210
          endpoint: 192.168.1.1:51820
          endpoint_public_key: ABCDEFG1234567890
          ips: 10.0.0.2/24
          allowed_ips: 0.0.0.0/0
